name: Argo CD GitOps CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Push the image
    runs-on: portfolio-runner-set

    steps:
      - name: Check out code
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./email-bun
          platforms: linux/amd64,linux/arm64
          push: true
          tags: akshaypranavkalathil/portfolio-email:${{ github.sha }} , akshaypranavkalathil/portfolio-email:latest
          cache-from: type=registry,ref=akshaypranavkalathil/portfolio-email:cache 
          cache-to: type=registry,ref=akshaypranavkalathil/portfolio-email:cache
  update:
    name: Update Helm Manifests
    runs-on: self-hosted
    needs: build

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          ref: infra
      - run: |
          chart_dir="chart"
          new_image_tag=${{ github.sha }}

          # Update the values.yaml file with the new image tag
          sed -i "s/^  tag: .*/  tag: $new_image_tag/" "$chart_dir/values.yaml"
          git config --global user.name 'Kallz02'
          git config --global user.email 'akshay.pranav.kalathil@gmail.com'
          git commit -a -m "updating image tag"
          git push 

